# Generated by Django 5.2.3 on 2025-06-28 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_metricrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("metric", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("threshold", models.FloatField(blank=True, null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("cleared_at", models.DateTimeField(blank=True, null=True)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="inventory.device",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["device", "timestamp"],
                        name="inventory_a_device__801994_idx",
                    )
                ],
            },
        ),
    ]
